spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/odf_edit_sample
    username: databaseuser
    password: databasepassword
doma:
  dialect: mysql
  doma.naming: SNAKE_LOWER_CASE
  sql-file-repository: no_cache
